[project]
name = "blokus-reinforcment-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sb3-contrib>=2.6.0",
    "stable-baselines3>=2.6.0",
]
